SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[Block] (
		[Floor]     [int] NOT NULL,
		[Code]      [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Block]
	ADD
	CONSTRAINT [PK__Block__95BCDB3D60A75C0F]
	PRIMARY KEY
	CLUSTERED
	([Floor], [Code])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[Block] SET (LOCK_ESCALATION = TABLE)
GO
