SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[Wellbeing] (
		[WellbeingID]     [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Wellbeing]
	ADD
	CONSTRAINT [PK_Wellbeing]
	PRIMARY KEY
	CLUSTERED
	([WellbeingID])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[Wellbeing] SET (LOCK_ESCALATION = TABLE)
GO
