SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[PatientUser] (
		[PatientID]     [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PatientUser]
	ADD
	CONSTRAINT [PK_Patient]
	PRIMARY KEY
	CLUSTERED
	([PatientID])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PatientUser] SET (LOCK_ESCALATION = TABLE)
GO
