SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[Patient] (
		[PatientID]     [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Patient]
	ADD
	CONSTRAINT [PK_Patient]
	PRIMARY KEY
	CLUSTERED
	([PatientID])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[Patient] SET (LOCK_ESCALATION = TABLE)
GO
