SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[Dietary] (
		[DietaryID]     [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Dietary]
	ADD
	CONSTRAINT [PK_Dietary]
	PRIMARY KEY
	CLUSTERED
	([DietaryID])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[Dietary] SET (LOCK_ESCALATION = TABLE)
GO
