SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[Vitals] (
		[VitalID]     [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Vitals]
	ADD
	CONSTRAINT [PK_Vitals]
	PRIMARY KEY
	CLUSTERED
	([VitalID])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[Vitals] SET (LOCK_ESCALATION = TABLE)
GO
