SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[Exercise] (
		[ExerciseID]     [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Exercise]
	ADD
	CONSTRAINT [PK_Exercise]
	PRIMARY KEY
	CLUSTERED
	([ExerciseID])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[Exercise] SET (LOCK_ESCALATION = TABLE)
GO
